In [1]:
import numpy as np
import pandas as pd

In [2]:
# ## [1,1,0,5],[1,0,0,4],[0,1,5,4]
R=np.array([[5,3,0,1],[4,0,0,1],])
num_users,num_items=R.shape
k=3
P = np.random.normal(scale=1/k, size=(num_users,k))
Q = np.random.normal(scale=1/k, size=(num_items,k))
print('P',P)
print('Q',Q)
print('R',R)

P [[ 0.87971044  0.24722306 -0.13840838]
 [ 0.16075561  0.45867482  0.69856148]]
Q [[-0.31586508 -0.13368587 -0.172719  ]
 [-0.21001784  0.29836012 -0.03329432]
 [-0.31357397  0.41231224 -0.0389786 ]
 [ 0.88666783 -0.11104982 -0.1398854 ]]
R [[5 3 0 1]
 [4 0 0 1]]


In [3]:
def matrix(R,P,Q,k,lr,epochs,Beta):
    '''
    lr is a learning Rate
    K is a Latent features of a Matrix
    epochs is Number of iterations    
    P=P and Q=Q.T (Shape of P dot Q.T should be equal to R)
    '''
    Q=Q.T
    
    '''
    How Matrix Notations Work Down below
    R[0][0]=np.dot(P[0,:],Q[:,0])
    
    '''
    for steps in range(1):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j]>0:
                    eij=R[i][j]-np.dot(P[i,:],Q[:,j])
                    
                    for K in range(k):
                        P[i][K]= P[i][K]+lr*(2*eij*Q[K][j] - Beta*P[i,K])
                        Q[K][j]=Q[K][j]+lr*(2*eij*P[i][K]- Beta*Q[K,j])
                        
        er_pred=np.dot(P,Q)
        
    return P,Q.T

In [4]:
matrix(R,P,Q,k=3,lr=.001,epochs=10000,Beta=.002)

(array([[ 0.87547192,  0.2476099 , -0.14050561],
        [ 0.15994885,  0.45734006,  0.69680241]]),
 array([[-0.3052587 , -0.12721414, -0.16830226],
        [-0.20458146,  0.29989802, -0.03416669],
        [-0.31357397,  0.41231224, -0.0389786 ],
        [ 0.8873929 , -0.11001249, -0.13854525]]))

In [5]:
np.dot(P,Q.T)

array([[-0.27509749, -0.10004699, -0.1669559 ,  0.76911377],
       [-0.22427932,  0.08062538,  0.11125073, -0.00491431]])