#### Categorical Encoding

##### one-Hot Encoding

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt   #Data visualisation libraries 
import seaborn as sns
%matplotlib inline

In [2]:
d = {'Gender': ['Yes','Yes','No','Yes','Yes','No','No','No','Yes','No','Yes']}
df = pd.DataFrame(data=d)

In [3]:
df['Yes']=np.where(df['Gender']=='Yes',1,0)
df['No']=np.where(df['Gender']=='No',1,0)
df

Gender  Yes  No
0     Yes    1   0
1     Yes    1   0
2      No    0   1
3     Yes    1   0
4     Yes    1   0
5      No    0   1
6      No    0   1
7      No    0   1
8     Yes    1   0
9      No    0   1
10    Yes    1   0

#### Weighted one-Hot Encoding

In [4]:
d = {'Gender': ['Yes','Yes','No','Yes','Yes','No','No','No','Yes','No','Yes']}
df = pd.DataFrame(data=d)
####################################################################################
def test(Series,variable):
    try:
        for r in variable:
            mydict1 = dict(zip(variable[r].unique(), (variable[r].value_counts()/len(variable)).values))
        for row in Series.unique():
            df[row]=np.where(Series==row,mydict1[row],0) 
        return  df
    
    except Exception:
        print('Error!! Dataframe has been changed')

test(Series=df['Gender'],variable=df)

Gender       Yes        No
0     Yes  0.545455  0.000000
1     Yes  0.545455  0.000000
2      No  0.000000  0.454545
3     Yes  0.545455  0.000000
4     Yes  0.545455  0.000000
5      No  0.000000  0.454545
6      No  0.000000  0.454545
7      No  0.000000  0.454545
8     Yes  0.545455  0.000000
9      No  0.000000  0.454545
10    Yes  0.545455  0.000000

#### Target Based One hot Mean encoding

In [5]:
d = {'Trend': ['Up','Up','Down','Flat','Down','Up','Down','Flat','Flat','Flat'],
      'Target':[21,24,8,15,11,26,12,16,14,13]}
df = pd.DataFrame(data=d)
df

Trend  Target
0    Up      21
1    Up      24
2  Down       8
3  Flat      15
4  Down      11
5    Up      26
6  Down      12
7  Flat      16
8  Flat      14
9  Flat      13

In [6]:
mydict={}
for k,v in (dict((df.groupby(df['Trend'])['Target'].apply(list)))).items():
    mydict[k]=np.mean(v)
    

In [7]:
for row in df['Trend'].unique():
    df[row]=np.where(df['Trend']==row,mydict[row],0)

In [8]:
df

Trend  Target         Up       Down  Flat
0    Up      21  23.666667   0.000000   0.0
1    Up      24  23.666667   0.000000   0.0
2  Down       8   0.000000  10.333333   0.0
3  Flat      15   0.000000   0.000000  14.5
4  Down      11   0.000000  10.333333   0.0
5    Up      26  23.666667   0.000000   0.0
6  Down      12   0.000000  10.333333   0.0
7  Flat      16   0.000000   0.000000  14.5
8  Flat      14   0.000000   0.000000  14.5
9  Flat      13   0.000000   0.000000  14.5

#### Target Based One hot Mean encoding 


In [9]:
d = {'Trend': ['Up','Up','Down','Flat','Down','Up','Down','Flat','Flat','Flat'],
      'Target':[21,24,8,15,11,26,12,16,14,13]}
df = pd.DataFrame(data=d)

In [10]:
mydict={}
for k,v in (dict((df.groupby(df['Trend'])['Target'].apply(list)))).items():
    mydict[k]=np.mean(v)

In [11]:
for row in df['Trend'].unique():
    df['mean']=np.where(df['Trend']==row,mydict[row],0)
df["mean"] = df["Trend"].map(mydict)

In [12]:
df

Trend  Target       mean
0    Up      21  23.666667
1    Up      24  23.666667
2  Down       8  10.333333
3  Flat      15  14.500000
4  Down      11  10.333333
5    Up      26  23.666667
6  Down      12  10.333333
7  Flat      16  14.500000
8  Flat      14  14.500000
9  Flat      13  14.500000

#### Working with Iris Dataset

#### One Hot Encoding Method

In [13]:
'''
Continous Variable=[sepal length,sepal width,petal length,iris]
###########
Iris-setosa
Iris-versicolor
Iris-virginica
############

Target Variable=[petal width]
'''
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [14]:
#colnames=['sepal length','sepal width','petal length','petal width','width']
iris_df=pd.read_csv('Iris.csv')
iris_df['iris'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
### One Hot Encoding
iris_df['Iris-setosa']=np.where(iris_df['iris']=='Iris-setosa',1,0)
iris_df['Iris-versicolor']=np.where(iris_df['iris']=='Iris-versicolor',1,0)
iris_df['Iris-virginica']=np.where(iris_df['iris']=='Iris-virginica',1,0)

In [16]:
iris_df.head()

sepal length  sepal width  petal length  petal width         iris  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

   Iris-setosa  Iris-versicolor  Iris-virginica  
0            1                0               0  
1            1                0               0  
2            1                0               0  
3            1                0               0  
4            1                0               0

In [17]:
iris_df_Y=iris_df['sepal length']
iris_df_X=iris_df[['petal width','sepal width','petal length','Iris-setosa','Iris-versicolor','Iris-virginica']]

### Train-Test Split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(iris_df_X,iris_df_Y, test_size=0.20, random_state=123,shuffle=True)

In [19]:
lm_ohe = LinearRegression()
lm_ohe.fit(x_train,y_train)
lm_ohe.coef_

array([-0.46321008,  0.51897615,  0.85765392,  0.50130528, -0.11323607,
       -0.38806921])

In [20]:
predictions = lm_ohe.predict(x_test)
predictions

array([6.28572098, 6.50704222, 6.44269137, 5.95172794, 4.94411883,
       6.0456475 , 5.84574081, 4.77816465, 4.7082372 , 6.04775466,
       6.12323625, 5.38290619, 5.5781833 , 6.64600524, 6.92899255,
       6.71801738, 4.93385749, 4.54915964, 6.36810166, 4.7138138 ,
       4.96772527, 6.33811147, 5.39655223, 6.13141289, 5.34684651,
       5.22502144, 4.96084865, 5.93497565, 7.90508683, 5.0715205 ])

In [21]:
print('MAE', mean_absolute_error(y_test, predictions),'\nRMSE',mean_squared_error(y_test, predictions))

MAE 0.28091366014206903 
RMSE 0.12337848770349531


#### Target Based One hot Mean encoding on iris

In [22]:
mydict={}
for k,v in (dict((iris_df.groupby(iris_df['iris'])['sepal length'].apply(list)))).items():
    mydict[k]=np.mean(v)

In [23]:
mydict

{'Iris-setosa': 5.006,
 'Iris-versicolor': 5.936,
 'Iris-virginica': 6.587999999999998}

In [24]:
for row in iris_df['iris'].unique():
    iris_df[row]=np.where(iris_df['iris']==row,mydict[row],0)

In [25]:

iris_df_Y=iris_df['sepal length']
iris_df_X=iris_df[['petal width','sepal width','petal length','Iris-setosa','Iris-versicolor','Iris-virginica']]
x_train, x_test, y_train, y_test = train_test_split(iris_df_X,iris_df_Y, test_size=0.20, random_state=123,shuffle=True)

In [26]:
lm_w_mean_oneHot = LinearRegression()
lm_w_mean_oneHot.fit(x_train,y_train)
lm_w_mean_oneHot.coef_

array([-0.46321008,  0.51897615,  0.85765392,  0.08297182, -0.03355532,
       -0.07195166])

In [27]:
predictions = lm_w_mean_oneHot.predict(x_test)
print('MAE', mean_absolute_error(y_test, predictions),'\nRMSE',mean_squared_error(y_test, predictions))

MAE 0.28091366014206887 
RMSE 0.12337848770349523
