# K-Nearest Neighbor for Regression

In [1]:
## Importing Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy.linalg import inv
from math import sqrt
from sklearn import preprocessing

In [2]:
df=pd.read_csv("auto-mpg.csv",low_memory=False)
df=df[['mpg','weight','acceleration','displacement']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 4 columns):
mpg             398 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
displacement    398 non-null float64
dtypes: float64(3), int64(1)
memory usage: 12.5 KB


In [3]:
from sklearn import preprocessing

x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
df.columns = ['mpg', 'weight','acceleration','displacement']
df.head()

mpg    weight  acceleration  displacement
0  0.239362  0.536150      0.238095      0.617571
1  0.159574  0.589736      0.208333      0.728682
2  0.239362  0.516870      0.178571      0.645995
3  0.186170  0.516019      0.238095      0.609819
4  0.212766  0.520556      0.148810      0.604651

In [4]:
## Target Variable
df_y=df['mpg']
#df_y.head()

In [5]:
## Independent Variables
df_x=df.drop('mpg', axis=1)
#df_x.head()

# Train-Test Split

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y, test_size=0.20, random_state=123)

In [8]:
distance=[]
def eucledianDistance(x_test,x_train):
    for i in range(len(x_test)):
        for j in range(len(x_train)):
            square_root=np.sum((x_train.iloc[j]-x_test.iloc[i])**2)
            distance.append(square_root)
eucledianDistance(x_test,x_train)

In [9]:
len(distance)

25440

In [10]:
def df_to_mat(distance):
    distance_matrix=np.asarray(distance).reshape((len(x_test), len(x_train)))
    return distance_matrix
distance_matrix=df_to_mat(distance)

In [12]:
Z_sort=[]
def sort():
    for i in range(len(distance_matrix)):
        Z_sort.append([x for _,x in sorted(zip(distance_matrix[i],y_train))])
sort()

In [14]:
## Changing list to array
Z_sort=np.asarray(Z_sort)
Z_sort

array([[0.50531915, 0.39893617, 0.67819149, ..., 0.13297872, 0.07978723,
        0.07978723],
       [0.10638298, 0.07978723, 0.10638298, ..., 0.53191489, 0.61170213,
        0.93085106],
       [0.30053191, 0.55319149, 0.43882979, ..., 0.13297872, 0.13297872,
        0.07978723],
       ...,
       [0.30585106, 0.30851064, 0.30585106, ..., 0.13297872, 0.13297872,
        0.07978723],
       [0.15957447, 0.25265957, 0.18617021, ..., 0.07978723, 0.13297872,
        0.13297872],
       [0.29787234, 0.18617021, 0.26861702, ..., 0.13297872, 0.13297872,
        0.07978723]])

In [15]:
## 7-Nearest Neighbour
regression_table=[]
def knnReg(k,Z_sort):
    for xx in range(len(Z_sort)):
        regression_table.append(np.mean(Z_sort[:,0:k][xx]))
knnReg(7,Z_sort)

In [25]:
## Changing List into Matrix
np.asarray(regression_table)

array([0.54027356, 0.11398176, 0.38639818, 0.63601824, 0.62348024,
       0.1899696 , 0.65349544, 0.54635258, 0.58320669, 0.12727964,
       0.50341945, 0.59992401, 0.25227964, 0.32028875, 0.25683891,
       0.2781155 , 0.15577508, 0.3662614 , 0.16907295, 0.13677812,
       0.64399696, 0.13487842, 0.693769  , 0.63639818, 0.28191489,
       0.27165653, 0.15577508, 0.48594225, 0.62348024, 0.46542553,
       0.43541033, 0.28951368, 0.42325228, 0.12537994, 0.4612462 ,
       0.67895137, 0.30547112, 0.62955927, 0.15957447, 0.68085106,
       0.1899696 , 0.72074468, 0.52773556, 0.55927052, 0.58092705,
       0.26025836, 0.0949848 , 0.43275076, 0.45136778, 0.64475684,
       0.13677812, 0.59612462, 0.58776596, 0.43541033, 0.50303951,
       0.30395137, 0.13297872, 0.48024316, 0.15387538, 0.45554711,
       0.59878419, 0.50113982, 0.74734043, 0.67211246, 0.4612462 ,
       0.47720365, 0.24848024, 0.65729483, 0.26785714, 0.59878419,
       0.1918693 , 0.27203647, 0.57028875, 0.5881459 , 0.26671

# Using Sklearn

In [19]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=7)
neigh.fit(x_train, y_train) 


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=7, p=2,
          weights='uniform')

In [20]:
y_expect=y_test
y_pred=neigh.predict(x_test)
y_pred

array([0.54027356, 0.11398176, 0.38639818, 0.63601824, 0.62348024,
       0.1899696 , 0.65349544, 0.54635258, 0.58320669, 0.12727964,
       0.50341945, 0.59992401, 0.25227964, 0.32028875, 0.25683891,
       0.2781155 , 0.15577508, 0.3662614 , 0.16907295, 0.13677812,
       0.64399696, 0.13487842, 0.693769  , 0.63639818, 0.28191489,
       0.27165653, 0.15577508, 0.48594225, 0.62348024, 0.46542553,
       0.43541033, 0.28951368, 0.42325228, 0.12537994, 0.4612462 ,
       0.67895137, 0.30547112, 0.62955927, 0.15957447, 0.68085106,
       0.1899696 , 0.72074468, 0.52773556, 0.55927052, 0.58092705,
       0.26025836, 0.0949848 , 0.43275076, 0.45136778, 0.64475684,
       0.13677812, 0.59612462, 0.58776596, 0.43541033, 0.50303951,
       0.30395137, 0.13297872, 0.48024316, 0.15387538, 0.45554711,
       0.59878419, 0.50113982, 0.74734043, 0.67211246, 0.4612462 ,
       0.47720365, 0.24848024, 0.65729483, 0.26785714, 0.59878419,
       0.1918693 , 0.27203647, 0.57028875, 0.5881459 , 0.26671

In [21]:
y_pred.shape

(80,)