# Neural Network From Scratch (Regression)

In [1]:
# Package imports
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import sklearn.linear_model
import matplotlib

# Display plots inline and change default figure size
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (10.0, 8.0)

In [2]:
## Building Data For Feeding into Neural network
X=np.array(([3,5],[5,1],[10,2],[5,2]),dtype=float)
y=np.array(([75],[82],[93],[99]),dtype=float)

In [3]:
"""
## FF
inputLayer=X.shape[1]
hiddenLayer=X.shape[0]
outputLayer=y.shape[1]
## Weight Initialization
w1 = np.random.randn(inputLayer,hiddenLayer)
w2 = np.random.randn(hiddenLayer,outputLayer)
z2=np.dot(X,w1)
a2=sigmoid(z2)
z3=np.dot(a2,w2)
yhat=sigmoid(z3)
yhat
## BP
delta1=np.multiply(-(y-yhat),sigmoidPrime(z3))
djdw2=(np.dot(delta1.T,a2)).T
djdw2
"""

'\n## FF\ninputLayer=X.shape[1]\nhiddenLayer=X.shape[0]\noutputLayer=y.shape[1]\n## Weight Initialization\nw1 = np.random.randn(inputLayer,hiddenLayer)\nw2 = np.random.randn(hiddenLayer,outputLayer)\nz2=np.dot(X,w1)\na2=sigmoid(z2)\nz3=np.dot(a2,w2)\nyhat=sigmoid(z3)\nyhat\n## BP\ndelta1=np.multiply(-(y-yhat),sigmoidPrime(z3))\ndjdw2=(np.dot(delta1.T,a2)).T\ndjdw2\n'

In [4]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputLayer=X.shape[1]
        self.hiddenLayer=X.shape[0]
        self.outputLayer=y.shape[1]
    ## Weight Initialization
        self.w1 = np.random.randn(self.inputLayer,self.hiddenLayer)
        self.w2 = np.random.randn(self.hiddenLayer,self.outputLayer)
    
    def sigmoid(self,z):
        return 1 / (1 + np.exp(-z))        
    
    def FF(self,X):
        ## From Input Layer to Hidden Layer
        self.z2=np.dot(X,self.w1)
        self.a2=self.sigmoid(self.z2)
        
        ## From Hidden layer to Output Layer
        self.z3=np.dot(self.a2,self.w2)
        y_hat=self.sigmoid(self.z3)
        return y_hat
    
    def J(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.y_hat = self.FF(X)
        J = 0.5*sum((y-self.y_hat)**2)
        return J
    
    def  sigmoidPrime(self,y):
         return (1 / (1 + np.exp(-y)))*(1-1 / (1 + np.exp(-y)))
        
    def BP(self, X, y):        
        self.y_hat=self.FF(X)
     ## djdw2 Derivative with respect of weight-2
    
        delta1=np.multiply(-(y-self.y_hat),self.sigmoidPrime(self.z3))
        djdw2=(np.dot(delta1.T,self.a2)).T
     ##  djdw1  Derivative with respect of weight-1
        delta2=np.multiply(np.dot(delta1,self.w2.T),self.sigmoidPrime(self.z2))
        djdw1=np.dot(X.T,delta2)
        return djdw1, djdw2

In [5]:
## Initialting the class
NN = NeuralNetwork()

In [6]:
## Cost Function
J = NN.J(X,y)
J

array([15225.39632991])

In [7]:
dJdW1, dJdW2 = NN.BP(X,y)

In [8]:
### Weight Matrix dw1 
dJdW1

array([[-1.03115662,  0.61621264,  0.00222532,  0.33247856],
       [-1.38311111,  0.65173284,  0.00156354,  0.07256971]])

In [9]:
### Weight Matrix dw2
dJdW2

array([[-2.20972708e+00],
       [-1.33712115e-01],
       [-2.11717961e-04],
       [-1.48751439e-01]])

In [10]:
### Gradient Descent for Neural Network
NN = NeuralNetwork()
max_iter=1000
iter=0

learning_rate=.01

while iter<max_iter:
    dJdW1,dJdW2=NN.BP(X, y)
    
    NN.w1=NN.w1-learning_rate*dJdW1
    NN.w2=NN.w2-learning_rate*dJdW2
    
    if iter%100==0:
        print(NN.J(X, y))
    
    iter=iter+1

[15099.57274349]
[15052.82455645]
[15052.66421726]
[15052.60994776]
[15052.58264564]
[15052.5662083]
[15052.55522593]
[15052.54736925]
[15052.54146998]
[15052.53687758]
